"""
Export utilities for generating reports and data exports.
"""
import io
from datetime import datetime


def generate_pdf_report(stats: dict, processed_data=None) -> bytes:
    """
    Generate a PDF report of the analysis.
    Uses basic HTML-to-PDF approach with simple formatting.
    
    Args:
        stats: Dictionary of statistics from the analysis
        processed_data: Optional DataFrame with processed data
    
    Returns:
        PDF file as bytes
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1e3a5f')
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.HexColor('#2d5a87')
        )
        
        normal_style = styles['Normal']
        
        story = []
        
        # Title
        story.append(Paragraph("Swale & Trench Placement Analysis Report", title_style))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal_style))
        story.append(Spacer(1, 20))
        
        # Data Summary Section
        story.append(Paragraph("Data Summary", heading_style))
        
        summary_data = [
            ["Metric", "Value"],
            ["Total Data Points", f"{stats.get('total_points', 'N/A'):,}"],
            ["Elevation Range", f"{stats.get('elevation_min', 0):.2f}m - {stats.get('elevation_max', 0):.2f}m"],
            ["Mean Elevation", f"{stats.get('elevation_mean', 0):.2f}m"],
        ]
        
        if stats.get('terrain_distribution'):
            for terrain, count in stats['terrain_distribution'].items():
                pct = stats['terrain_percentages'].get(terrain, 'N/A')
                summary_data.append([f"{terrain} Count", f"{count} ({pct})"])
        
        table = Table(summary_data, colWidths=[2.5*inch, 3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a5f')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#334155')),
            ('FONTSIZE', (0, 1), (-1, -1), 11),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e8eaed')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        story.append(table)
        story.append(Spacer(1, 30))
        
        # Interpretation
        story.append(Paragraph("Interpretation", heading_style))
        story.append(Paragraph(
            "<b>Swales</b> (shown in green on the map) represent lower elevation areas "
            "suitable for water collection. These depressions naturally gather runoff "
            "and are ideal locations for water harvesting structures.",
            normal_style
        ))
        story.append(Spacer(1, 10))
        story.append(Paragraph(
            "<b>Trenches</b> (shown in blue on the map) represent higher elevation areas "
            "where drainage channels should be constructed to direct water flow toward "
            "the swales.",
            normal_style
        ))
        story.append(Spacer(1, 30))
        
        # Footer note
        story.append(Paragraph(
            "<i>This report was generated by the Swale & Trench Placement Tool. "
            "For detailed visualization, please refer to the interactive map and contour analysis.</i>",
            ParagraphStyle('Footer', parent=normal_style, fontSize=9, textColor=colors.gray)
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
        
    except ImportError:
        # Fallback if reportlab is not installed
        return generate_text_report(stats).encode('utf-8')


def generate_text_report(stats: dict) -> str:
    """
    Generate a text-based report as fallback.
    """
    report = f"""
================================================================================
           SWALE & TRENCH PLACEMENT ANALYSIS REPORT
================================================================================

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

DATA SUMMARY
------------
Total Data Points:  {stats.get('total_points', 'N/A'):,}
Elevation Range:    {stats.get('elevation_min', 0):.2f}m - {stats.get('elevation_max', 0):.2f}m
Mean Elevation:     {stats.get('elevation_mean', 0):.2f}m
"""
    
    if stats.get('terrain_distribution'):
        report += "\nTERRAIN CLASSIFICATION\n----------------------\n"
        for terrain, count in stats['terrain_distribution'].items():
            pct = stats['terrain_percentages'].get(terrain, 'N/A')
            report += f"{terrain}: {count} points ({pct})\n"
    
    report += """
INTERPRETATION
--------------
SWALES (green on map): Lower elevation areas suitable for water collection.
These depressions naturally gather runoff and are ideal for water harvesting.

TRENCHES (blue on map): Higher elevation areas where drainage channels should
be constructed to direct water flow toward the swales.

================================================================================
Report generated by Swale & Trench Placement Tool
================================================================================
"""
    return report
